### ISSUE TITLE
feature request - Add fantasy dice

### ISSUE THREAD

**Issue by holsat** [veysholdt/veysholdt.github.io#1]
This is a feature request to add different sided dice, 30 sided, 20 sided, 10 sided, 8 sided and 4 sided. With this, Miro could be used to place some table top RPG's, which would be very cool.

**Comment by veysholdt** [comment]
I'll look into it.

**Comment by veysholdt** [comment]
I just updated the app. You can now create dice with a custom number of sides. I'd love to hear your feedback.

**Comment by holsat** [comment]
Its going in the right direction. Typically people playing games that require these type of dice want to do so quickly. Instead of doing a custom dice checkbox where you enter a number of sides, it would be preferable to add the different standard dice types that I mentioned above, particularly the d20, d12, d10, d8 and d4 (oops looks like I missed d12 above) d30 isn't often used.

Also, I did notice that while moving the slider, sometimes a 0 came up. You'll need to make sure the smallest number is 1.

That at least would be a good start. Perhaps have each with their own slider to select the number of dice? Would be very cool if you could get vector images of the different dice shapes to put the number rolled into. (I think for the d6 you are just using the unicode characters?) I'm not a web developer so I don't know how difficult it would be to do that.

**Comment by veysholdt** [comment]
Thank for your feedback! I applied new changes to the app. You can now quickly select the number of dice directly without having to input the number manually and I fixed the bug with the 0 coming up.

However, I think when adding a slider for each number of sides would make the UI to overloaded.

Yes, for d6 I just use unicode. The problem with creating custom shapes is, they would have to be added as images to the board and I am not sure about the resulting impact on performance. At the moment the dice are added as text basically, which is not very expensive.

**Comment by holsat** [comment]
Ok, thank you very much, it works!

**Comment by veysholdt** [comment]
I'm happy to hear that! I'll close the issue then.
